### ISSUE TITLE
idea: Compile time switch?

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/SHT31_SW#7]
Just tested this with a SHT31 connected to ATTINY84 @ 1MHz with several I2C speeds and slow/fast reading mode.
SoftWire fails for me, SoftWarewire works.

Maybe add compile switch or #define to switch more easily between these libraries.

_Originally posted by @alecks68 in https://github.com/RobTillaart/SHT31_SW/issues/5#issuecomment-1640249734_

**Comment by RobTillaart** [comment]
@alecks68

Created a new issue to discuss this idea in its own context.

I created this branch - https://github.com/RobTillaart/SHT31_SW/tree/SoftwareWire-version-0.2.0-%3D%3D-AVR-only
in the past but I am not happy yet. It are two different solutions for the same problem and one does not work on AVR and the other on AVR only,

An option I considered was to create a new repo called **SHT31_SWW** for the softWareWire version.
As the SHT31 lib is quite stable, having a few "shadow" repos is not a lot of extra work.

Opinion?

**Comment by alecks68** [comment]
Hi Rob, I have to admit that I do not have experience with branching, merging and version control on github. I also do not have good knowledge on platformio dependencies.

From user perspective I think it would be great to just include one library tailored to the purpose, i.e. SHT31_SW or SHT31_SWW or SHT_31. This is most likely also the fastest and safest way forward.
Said that -- and not knowing enough about platformio library design -- I had to include dependencies myself, i.e. : 
       robtillaart/SHT31_SW@^0.1.1
	robtillaart/SHT31 @ ^0.3.8
	testato/SoftwareWire @ ^1.6.0

From maintenance effort perspective it could be better to directly adapt SHT31 to support wire, softwire and softwarewire or at least to slim down the wrapper to a minimum by e.g. separating begin(), beginTransmission(), EndTransmission, read(), write(), requestFrom() in SHT31 and then just wrapping these.

In general this seems to be a standard problem of I2C devices that rely on wire.h. I wanted to use a APDS9930 with SoftwareWire and ended up writing a wrapper as you did.

For the differences between softWire and softwareWire a first test approach could be to check with a digital analyzer the exact output and timing on the bus for each. Something I noted on my list for long winter evenings...

**Comment by RobTillaart** [comment]
OK, will add another repo called **SHT31_SWW** as that is a straightforward solution.
Might take a few days as other tasks have priority.

**Comment by RobTillaart** [comment]
Created - https://github.com/RobTillaart/SHT31_SWW as placeholder.
Think this issue can be closed.
If needed open a new issue in the new repo.

**Comment by RobTillaart** [comment]
@alecks68 
Created a 0.1.0 version of https://github.com/RobTillaart/SHT31_SWW using SoftwareWire .
There are a few open ends incl documentation and build-CI. 
Still it should be usable for UNO.

(discussion can be at other repo if needed)
